const actions = {
    SET_USER_CREDENTIALS : "SET_USER_CREDENTIALS",
    SET_LOGGED_STATUS : "SET_LOGGED_STATUS",
    SET_USER_DETAILS : "SET_USER_DETAILS",
    SET_FOOD_DETAILS: "SET_FOOD_DETAILS",
    SET_BREAK_DETAILS :"SET_BREAK_DETAILS",
    SET_EVENING_DETAILS : "SET_EVENING_DETAILS",
    SET_CENTERS : "SET_CENTERS"
  };
  
  export default actions;
  